# Default values for the chart
postgres:
  enabled: true
  image: postgres:16-alpine
  db:
    name: tiiassessmentdb
    user: tiiassessmentuser
    password: dontforgettoprotectme
  persistence:
    enabled: false

mosquitto:
  enabled: true
  image: eclipse-mosquitto:2.0

simulator:
  enabled: true
  image: simulator:latest
  env:
    MQTT_BROKER_URL: "mqtt://mosquitto:1883"
    MQTT_TOPIC: "iot/data"
    PUBLISH_INTERVAL_MS: "2000"  

backend:
  enabled: true
  image: backend:latest
  replicas: 1
  env:
    MQTT_BROKER_URL: "mqtt://mosquitto:1883"
    MQTT_TOPIC: "iot/data"
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_USER: "tiiassessmentuser"
    DB_NAME: "tiiassessmentdb"
    # Important: For local development, create a secret manually:
    # kubectl create secret generic db-secret --from-literal=DB_PASSWORD=<password>
    # For cloud, the password is managed automatically by RDS
    DB_PASSWORD_SECRET_NAME: "db-secret"
    PORT: "3000"
    DB_SSL: "false"
    CONSUME_SQS: "false"
    AWS_SQS_URL: ""
    AWS_REGION: ""

    
prometheus:
  enabled: true
  image: prom/prometheus:latest

grafana:
  enabled: true
  image: grafana/grafana:latest

# External Secrets Operator configuration
externalSecrets:
  enabled: false
  aws:
    region: "us-east-1"
