# This values-cloud.yaml is used to override the default values for the chart

# in this demo, I will disable all services except backend, prometheus and grafana
# because I will use the cloud services for the rest
postgres:
  enabled: false

mosquitto:
  enabled: false
simulator:
  enabled: false

backend:
  image: <account-id>.dkr.ecr.<region>.amazonaws.com/backend:latest
  replicas: 3
  iamRoleArn: "arn:aws:iam::<account-id>:role/eks-backend-sa-role"
  env:
    MQTT_BROKER_URL: "ssl://<iot-endpoint>:8883" # this is the endpoint of the IoT Core
    MQTT_TOPIC: "iot/data"
    DB_HOST: "<rds-endpoint>" # this is the endpoint of the RDS instance
    DB_PORT: "5432"
    DB_NAME: "tiiassessment"
    DB_USER: "tiiassessment"
    # Here I'm using External Secrets Operator to get the password from AWS Secrets Manager
    DB_PASSWORD_SECRET_NAME: "tii-assessment/db-password"
    DB_PASSWORD_SECRET_KEY: "DB_PASSWORD"
    PORT: "3000"

prometheus:
  enabled: true

grafana:
  enabled: true

# External Secrets Operator configuration for cloud deployment
externalSecrets:
  enabled: true
  aws:
    region: "<region>"



