# Default values for the chart
postgres:
  enabled: true
  image: postgres:16-alpine
  db:
    name: tiiassessment
    user: tiiassessment
    password: dontforgettoprotectme
  persistence:
    enabled: false

mosquitto:
  enabled: true
  image: eclipse-mosquitto:2.0

simulator:
  enabled: true
  image: simulator:latest
  env:
    MQTT_BROKER_URL: "mqtt://mosquitto:1883"
    MQTT_TOPIC: "iot/data"
    PUBLISH_INTERVAL_MS: "2000"  

backend:
  enabled: true
  image: backend:latest
  replicas: 1
  env:
    MQTT_BROKER_URL: "mqtt://mosquitto:1883"
    MQTT_TOPIC: "iot/data"
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_USER: "tiiassessment"
    DB_NAME: "tiiassessment"
    # Important: I will not store the password in the values.yaml file, as it is not a good practice
    # I will use a secret to store the password, and then I will reference it in the values.yaml file
    # Don't forget to create the secret in the local cluster or in the cloud  
    # example for local cluster: kubectl create secret generic db-secret --from-literal=DB_PASSWORD=<password>
    # example for cloud: aws secretsmanager create-secret --name db-secret --secret-string '{"DB_PASSWORD":"<password>"}'
    DB_PASSWORD_SECRET_NAME: "db-secret"
    DB_PASSWORD_SECRET_KEY: "DB_PASSWORD"
    PORT: "3000"
  
prometheus:
  enabled: true
  image: prom/prometheus:latest

grafana:
  enabled: true
  image: grafana/grafana:latest
