# This values-local.yaml is used to override the default values for the chart
# in this demo, I will enable all services as they are running locally in kind cluster (docker desktop)
postgres:
  enabled: true

mosquitto:
  enabled: true

simulator:
  enabled: true
  env:
    MQTT_BROKER_URL: "mqtt://mosquitto:1883"

backend:
  env:
    MQTT_BROKER_URL: "mqtt://mosquitto:1883"
    DB_HOST: "postgres"
    # Important: I will not store the password in the values-local.yaml file, as it is not a good practice
    # I will use a secret to store the password, and then I will reference it in the values-local.yaml file
    # Don't forget to create the secret in the local cluster
    # example for local: kubectl create secret generic db-secret --from-literal=DB_PASSWORD=<password>
    DB_PASSWORD_SECRET_NAME: "db-secret"
    DB_PASSWORD_SECRET_KEY: "DB_PASSWORD"
    PORT: "3000"
    DB_SSL: "false"

prometheus:
  enabled: true

grafana:
  enabled: true

# External Secrets Operator configuration for local deployment
externalSecrets:
  enabled: false

