# This values-cloud.yaml is used to override the default values for the chart

# in this demo, I will disable all services except backend, prometheus and grafana
# because I will use the cloud services for the rest
postgres:
  enabled: false

mosquitto:
  enabled: false

simulator:
  enabled: false

backend:
  image: <sua-conta>.dkr.ecr.eu-west-1.amazonaws.com/backend:latest
  replicas: 3
  env:
    MQTT_BROKER_URL: "ssl://<endpoint-iot-core>:8883"
    MQTT_TOPIC: "iot/data"
    DB_HOST: "<endpoint-rds>"
    DB_PORT: "5432"
    DB_NAME: "tiiassessment"
    DB_USER: "tiiassessment"
    # Important: I will not store the password in the values-cloud.yaml file, as it is not a good practice
    # I will use a secret to store the password, and then I will reference it in the values-cloud.yaml file
    # Don't forget to create the secret in the cloud
    # example for cloud: aws secretsmanager create-secret --name db-secret --secret-string '{"DB_PASSWORD":"<password>"}'
    DB_PASSWORD_SECRET_NAME: "db-secret"
    DB_PASSWORD_SECRET_KEY: "DB_PASSWORD"
    PORT: "3000"

prometheus:
  enabled: true

grafana:
  enabled: true
