{{- if and .Values.backend.enabled .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-password-external-secret
  namespace: default
  labels:
    app: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: db-password-secret
    type: Secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.backend.env.DB_PASSWORD_SECRET_NAME }}
        property: {{ .Values.backend.env.DB_PASSWORD_SECRET_KEY }}
{{- end }} 