# Service
{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
  type: ClusterIP # I'm using ClusterIP for this assessment so it cannot be accessed from outside the cluster
{{- end }}