{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    # Basic Mosquitto configuration for IoT testing
    listener 1883
    allow_anonymous true
    
    # Logging
    log_type all
    log_timestamp true
    
    # Persistence
    persistence true
    persistence_location /mosquitto/data/
    
    # Security (disabled for testing)
    # password_file /mosquitto/config/password_file
{{- end }} 