{{- if and .Values.backend.enabled .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: default
  labels:
    app: backend
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: backend-sa
{{- end }} 